os: osx
language: objective-c
osx_image: xcode10.2
xcode_project: KeyValueObservation.xcodeproj

before_install:
  - gem install cocoapods

script:
  - set -o pipefail && travis_retry xcodebuild -scheme "KeyValueObservation" -destination "platform=iOS Simulator,name=iPhone XS Max" -configuration Test ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - set -o pipefail && travis_retry xcodebuild -scheme "KeyValueObservation tvOS" -destination "platform=tvOS Simulator,name=Apple TV 4K" -configuration Test ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - set -o pipefail && travis_retry xcodebuild -scheme "KeyValueObservation watchOS" -destination "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm" -configuration Debug ONLY_ACTIVE_ARCH=YES
  - set -o pipefail && travis_retry xcodebuild -scheme "KeyValueObservation macOS" -destination "platform=macOS" -configuration Test ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
