name: Carthage
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
      LOGFILE: /tmp/.keyvalueobservation.carthage.xcodebuild.log

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        touch "$LOGFILE"

    - name: Install Carthage
      run: |
        brew update
        brew install carthage

    - name: Create Cartfile
      run: |
        # Delete all of the old tags (if any) and create a new tag for building
        git tag | xargs git tag -d
        git tag 1.0
        
        echo "git \"file://$(pwd)\"" > ./Cartfile

    - name: Build
      run: |
        ./scripts/carthage.sh update --log-path "$LOGFILE"

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: BuildLog
        path: ${{ env.LOGFILE }}
