name: Cocoapods
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  lint:
    strategy:
      matrix:
        linttype: [Dynamic, Static]

    name: Lint
    runs-on: macOS-latest
    env:
      LOGSDIR: /tmp/.keyvalueobservation.cocoapods/Logs
      LINT_TYPE: ${{ matrix.linttype }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        mkdir -p "$LOGSDIR"

    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Lint
      run: |
        if [ "$LINT_TYPE" == "Dynamic" ]; then
            pod lib lint --verbose 2>&1 | tee "$LOGSDIR/PodLint-$LINT_TYPE.log"
        else
            pod lib lint --verbose --use-libraries 2>&1 | tee "$LOGSDIR/PodLint-$LINT_TYPE.log"
        fi

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Logs
        path: ${{ env.LOGSDIR }}/*.log
