name: Cocoapods
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  lint:
    strategy:
      matrix:
        linttype: [Dynamic, Static]

    name: Lint
    runs-on: macOS-latest
    env:
      LINT_TYPE: ${{ matrix.linttype }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Lint
      run: |
        if [ "$LINT_TYPE" == "Dynamic" ]; then
            pod lib lint
        else
            pod lib lint --use-libraries
        fi
