name: Upload Assets
on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Assets
    runs-on: macOS-latest
    env:
      TMPDIR: /tmp/.keyvalueobservation.xcframework.build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./scripts/xcframework.sh -output ${TMPDIR}/KeyValueObservation.xcframework

    - name: Create Zip
      run: |
        cd ${TMPDIR}
        zip -rX KeyValueObservation.xcframework.zip KeyValueObservation.xcframework

    - name: Upload Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.TMPDIR }}/KeyValueObservation.xcframework.zip
        asset_name: KeyValueObservation.xcframework.zip
        asset_content_type: application/zip

    - name: Create Tar
      run: |
        cd ${TMPDIR}
        tar -zcvf KeyValueObservation.xcframework.tar.gz KeyValueObservation.xcframework

    - name: Upload Tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.TMPDIR }}/KeyValueObservation.xcframework.tar.gz
        asset_name: KeyValueObservation.xcframework.tar.gz
        asset_content_type: application/gzip
