name: XCFramework
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
      TMPDIR: /tmp/.keyvalueobservation.xcframework.build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./scripts/xcframework.sh --output ${TMPDIR}/KeyValueObservation.xcframework
