name: XCFramework
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**' # Ignore all files under '.github'
      - '!.github/workflows/xcframework.yml' # Except for this workflow
      - '.gitignore'
      - '.remarkrc'
      - 'codecov.yml'
      - 'KeyValueObservation.podspec'
      - 'LICENSE'
      - 'README.md'
      - 'Tests/**'

jobs:
  build:
    name: Build
    runs-on: macOS-11
    env:
      TMPDIR: /tmp/.keyvalueobservation.xcframework.build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        mkdir -p "${TMPDIR}/Output"
        mkdir -p "${TMPDIR}/Logs"

    - name: Build
      run: |
        ./scripts/xcframework.sh --build-dir "${TMPDIR}"

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: BuildLogs
        path: ${{ env.TMPDIR }}/Logs/*.log
